server:
  port: 8880

spring:
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: update
#    database-platform: io.innospots.server.base.CustomDialect
    show-sql: true
    generate-ddl: false



innospots:
  config:
    host: http://www.innospots.com:8000
  db:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    jdbc-url: jdbc:mysql://${DB_IP}:${DB_PORT:3306}/${DB_NAME}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=${DB_TIMEZONE:GMT%2B8}&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximum-pool-size: 64
    minimum-idle: 4
    pool-name: innospots-pool
    max-lifetime: 1800000
    idle-timeout: 600000 # millisecond,default ten minute

  application:
    visitor:
      workflowAddress: ${spring.cloud.client.ip-address}:${server.port}
      workflowTestAddress: ${spring.cloud.client.ip-address}:${server.port}