server:
  port: 9800

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: false
    open-in-view: false

innospots:
  db:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:${INNOS_ROOT};MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    maximum-pool-size: 64
    minimum-idle: 4
    pool-name: innospots-pool
    max-lifetime: 1800000
    idle-timeout: 600000 # millisecond,default ten minute
