innospots:
  security:
    enabled: true
    mode: EXHIBITION
    tokenSigningKey: 696e6e6f73706f74732d323032342d39
    tokenIssuer: innospots
    tokenExpTimeMinute: 180
    open-super-admin-permission: true
    ignore-auth-paths:
      - /innospots/apps/api/page/**
      - /innospots/apps/api/data/**
      - /innospots/api/workflow/runtime/webhook/**
      - /actuator/health
      - /actuator/info
      - /actuator/**
      - /error
      - /doc.html
      - /webjars/**
      - /isp/webhook/**
      - /docs/**
      - /manual/**
      - /**/swagger-ui/**
      - /h2-console/**
      - /**/v3/api-docs/**
      - /swagger-resources/**
      - /innospots/api/login-auth/**
      - /innospots/api/temp-token/**
      - /innospots/api/i18n/locale/**/*.json
      - /innospots/api/i18n/locale/**
      - /innospots/api/i18n/language/list
      - /innospots/api/test/**
      - /innospots/api/image/**
      - /innospots/api/workflow/flow-execution/resources/**
      - /innospots/api/workflow/sse/**
      - /innospots/api/workflow/stream/**
      - /innospots/api/oauth2/callback/**
      - /
      - /403
      - /*.svg
      - /*.less
      - /*.png
      - /*.js
      - /*.css
      - /*.json
      - /*.html
      - /static/**
      - /icons/**
      - /favicon.ico
      - /locales/**
      - /apps/**
      - /js/**
      - /dashboard/image/**
      - /monitor/**
      - /monitor
    ignore-permission-paths:
      - /innospots/api/auth-token/**
      - /innospots/api/access/**
      - /innospots/api/navigation/items
      - /innospots/api/data-sets/options/**
      - /innospots/api/data-set/data/**
      - /innospots/api/data-set/**
      - /innospots/api/http/third/test/**
      - /innospots/api/test/**
      - /innospots/api/operate-log/**
      - /innospots/api/workspace/**
      - /innospots/api/login-log/**
      - /innospots/api/user/**